version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - vavalm-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
      additional_contexts:
         parent_dir: ./
    restart: always
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      PORT: 8000
    networks:
      - vavalm-network
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
      additional_contexts:
         parent_dir: ./
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    networks:
      - vavalm-network
    depends_on:
      - backend

networks:
  vavalm-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local